#!/bin/sh

set -e

# detect user: first try to use lpg-load-balancer
for USER in lpg-load-balancer; do
  if id -u "$USER" >/dev/null 2>/dev/null; then
    echo "lpg-load-balancer: detected user $USER"
    break
  fi
done

# create user if doesn't exist: it will create lpg-load-balancer if not found
if ! id -u "$USER" >/dev/null 2>/dev/null; then
  echo "lpg-load-balancer: creating $USER..."
  useradd --shell /bin/bash --comment --create-home $USER
fi

# get USER home directory
eval HOMEDIR=~$USER

# create empty config and re-register runner
mkdir -p /etc/lpg-load-balancer
chmod 0700 /etc/lpg-load-balancer
if [ -f $HOMEDIR/config.toml ] && [ ! -f /etc/lpg-load-balancer/config.toml ]; then
  echo "lpg-load-balancer: importing configuration to /etc/lpg-load-balancer/config.toml"
  cp $HOMEDIR/config.toml /etc/lpg-load-balancer/config.toml
  chmod 0600 /etc/lpg-load-balancer/config.toml
fi

# uninstall old service
lpg-load-balancer stop --service="lpg-load-balancer" >/dev/null 2>/dev/null || :
lpg-load-balancer uninstall --service="lpg-load-balancer" >/dev/null 2>/dev/null || :

# re-register runner
lpg-load-balancer stop >/dev/null 2>/dev/null || :
lpg-load-balancer uninstall >/dev/null 2>/dev/null || :
lpg-load-balancer install --user=$USER --working-directory=$HOMEDIR

# todo: tune /etc/sysctl.conf
# net.ipv4.tcp_tw_reuse = 1
# net.ipv4.tcp_tw_recycle = 1
# net.ipv4.ip_local_port_range = 50000
# ulimit -n 102400
# /etc/security/limits.d?

# start runner service
lpg-load-balancer start || :
